CREATE TABLE films (
  id SERIAL PRIMARY KEY,
  selected_collections TEXT,
  title TEXT NOT NULL, 
  director TEXT,
  writers TEXT,
  stars TEXT,
  year_released TEXT,
  genre TEXT,
  film_format TEXT,
  film_version TEXT,
  film_condition TEXT,
  film_value TEXT,
  film_rating TEXT,
  selling BOOLEAN DEFAULT FALSE,
  trailer TEXT,
  tags TEXT,
  notes TEXT,
  memorable_scenes TEXT,
  date_added DATE DEFAULT CURRENT_DATE NOT NULL
);