CREATE TABLE users (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE films
  ADD COLUMN
    user_id INTEGER REFERENCES users(user_id)
    ON DELETE SET NULL;

ALTER TABLE collections
  ADD COLUMN
    user_id INTEGER REFERENCES users(user_id)
    ON DELETE SET NULL;

ALTER TABLE film_collections
  ADD COLUMN
    user_id INTEGER REFERENCES users(user_id)
    ON DELETE SET NULL;
